Feat(27): storysecurisation
LeNelSoN/you-are-the-hero pull request #32
Opened 2024-10-03 14:16 UTC by padabou

[X] Update the story creation endpoint to check if the user has the "Editor" role before allowing story creation. 🔒
[X] Update the story modification endpoint to enforce the same role restriction, ensuring only editors can modify existing stories.
[X] Implement role checks in the relevant service classes to verify the user's permissions.
[X] Write unit tests to validate that only users with the "Editor" role can create or modify stories, and that appropriate error messages are returned for unauthorized attempts.

2024-10-03 20:59 UTC, LeNelSoN requested changes

2024-10-04 07:01 UTC, padabou commented on src/main/java/fr/nelson/you_are_the_hero/model/db/Story.java
> +        return createdBy;
MongoDB is not a relational database system, it offer to join some collection but it's not the way, and it's clearly impact performance, you can read some stuff here : https://www.dragonflydb.io/faq/mongodb-dbref-performance

Btw, if you prefer a dbref, i'll implement a dbref

2024-10-04 10:23 UTC, LeNelSoN commented on src/main/java/fr/nelson/you_are_the_hero/model/db/Story.java
> +        return createdBy;
Okay, let's go with that approach. We can manage it more effectively and avoid unnecessary data.

2024-10-04 12:02 UTC, LeNelSoN approved these changes

2024-10-04 12:03 UTC, merged